version: '3.5'
services:

  zabbix:
    container_name: $BACKEND_CONTAINER_NAME
    hostname: $BACKEND_HOSTNAME
    image: $BACKEND_IMAGE_NAME
    restart: $RESTART_STATE
    links:
      - mysql
    ports:
      - "10051:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=Zabbix@@2024
      #- MYSQL_ROOT_PASSWORD=Zabbix@@2024
      - ALLOWUNSUPPORTEDDBVERSIONS=1
    depends_on:
      - mysql
    stop_grace_period: 5s
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000
      - net.ipv4.conf.all.accept_redirects=0
      - net.ipv4.conf.all.secure_redirects=0
      - net.ipv4.conf.all.send_redirects=0

  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:8.0-oracle
    init: true
    restart: always
    environment:
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=Zabbix@2024
      - MYSQL_ROOT_PASSWORD=Zabbix@@2024
      - MYSQL_ROOT_HOSTS=%
      - MYSQL_DATABASE=zabbix
      - MYSQL_CHARSET=utf8
      - MYSQL_COLLATION=utf8mb4_unicode_ci
      #- MYSQL_ALLOW_EMPTY_PASSWORD=true
    tmpfs: /tmp
    ports:
      - "3306:3306"
    volumes:
       - "./mysql-data:/var/lib/mysql"
       - "./zabbix/init_db.sql:/docker-entrypoint-initdb.d/zabbix"
    stop_grace_period: 1m

  nginx:
    container_name: nginx
    hostname: nginx
    image: zabbix/zabbix-web-nginx-mysql:ubuntu-6.4-latest
    restart: always
    links:
      - mysql
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - PHP_TZ="Europe/London"
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=Zabbix@2024
      - HOSTNAME=Zabbix
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    stop_grace_period: 10s
    depends_on:
      - mysql
    sysctls:
      - net.core.somaxconn=65535




#env_file:
# - ./zabbix/.env_web
# - ./zabbix/.env_db_mysql
# - ./zabbix/.env_srv
#command: --default-authentication-plugin=mysql_native_password
#command: --skip-grant-tables
#command: --skip-networking
#command: --ignore-db-dir=lost+found
#command: --initialize-insecure
#command: --disable-partition-engine-check
# zabbix/zabbix-server-mysql:ubuntu-6.4.11-latest

# => db:
  # CREATE USER 'zabbix'@'%' IDENTIFIED with 'Zabbix@2024';
  # GRANT ALL ON *.* TO 'zabbix'@'%';
  # REVOKE ALL ON *.* TO 'zabbix'@'%';
  # DROP USER 'zabbix'@'%';
  # DELETE FROM mysql.user where USER='zabbix' and HOST='%';
  # FLUSH PRIVILEGES;
  # CREATE USER 'zabbix'@'%' IDENTIFIED with 'Zabbix@2024';
