---

- name: Creat Container 
  hosts: all
  become: true
  gather_facts: true
  
  tasks:
    
    - name: "Install Basic Packages"
      apt:
        name: "{{ item }}"
        state: "installed"
        with_items:
          - wget
          - python-pip
          - curl
          - vim
    
    - name: "Pip install docker-py"
      pip:
        name: docker-py
        state: present
    # Install Docker via convenience script - latest version
    
    - name: "Install Docker"
      command: 'bash -c "curl -fsSL https://get.docker.com/ | sh"'
    
    - name: "Pull Nginx Docker image and run it"
      docker_container:
        name: nginx-bloggy
        image: nginx
        state: started
        restart: yes
        restart_policy: always
        ports:
          - "80:80"
