# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_internet_gateway.igw-06fcd611034e99d14:
resource "aws_internet_gateway" "myigw" {
  count  = var.acount
  tags   = {}
  vpc_id = aws_vpc.main_vpm[acount.index].id
}
