# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table_association.rtbassoc-01b2fe2ddfac5825c:
resource "aws_route_table_association" "myrtbassociation2" {
  count          = var.acount
  route_table_id = aws_route_table.rtb1-natgw-tgw[acount.index].id
  subnet_id      = aws_subnet.private_subnet[acount.index].id
}
